version: '3.6'
name: ms-backend

services:
  db:
    build: ./database
    container_name: DEV_POSTGRES
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
